version: "3.9"

services:

  catsdogs-api:
    image: catsdogs-api
    container_name: catsdogs-api-container
    ports:
      - "8000:8000"
    environment:
      - DEPLOY_ENV=local

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3000:3000"
 